/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EstimatingEstimatesRouteImport } from './routes/estimating.estimates'
import { Route as CrmCustomersRouteImport } from './routes/crm.customers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimatingEstimatesRoute = EstimatingEstimatesRouteImport.update({
  id: '/estimating/estimates',
  path: '/estimating/estimates',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmCustomersRoute = CrmCustomersRouteImport.update({
  id: '/crm/customers',
  path: '/crm/customers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crm/customers': typeof CrmCustomersRoute
  '/estimating/estimates': typeof EstimatingEstimatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crm/customers': typeof CrmCustomersRoute
  '/estimating/estimates': typeof EstimatingEstimatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crm/customers': typeof CrmCustomersRoute
  '/estimating/estimates': typeof EstimatingEstimatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/crm/customers' | '/estimating/estimates'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/crm/customers' | '/estimating/estimates'
  id: '__root__' | '/' | '/crm/customers' | '/estimating/estimates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrmCustomersRoute: typeof CrmCustomersRoute
  EstimatingEstimatesRoute: typeof EstimatingEstimatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimating/estimates': {
      id: '/estimating/estimates'
      path: '/estimating/estimates'
      fullPath: '/estimating/estimates'
      preLoaderRoute: typeof EstimatingEstimatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/customers': {
      id: '/crm/customers'
      path: '/crm/customers'
      fullPath: '/crm/customers'
      preLoaderRoute: typeof CrmCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrmCustomersRoute: CrmCustomersRoute,
  EstimatingEstimatesRoute: EstimatingEstimatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
