/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsActiveRouteImport } from './routes/projects.active'
import { Route as PipelineTrackingRouteImport } from './routes/pipeline.tracking'
import { Route as EstimatingEstimatesRouteImport } from './routes/estimating.estimates'
import { Route as CrmCustomersRouteImport } from './routes/crm.customers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsActiveRoute = ProjectsActiveRouteImport.update({
  id: '/projects/active',
  path: '/projects/active',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineTrackingRoute = PipelineTrackingRouteImport.update({
  id: '/pipeline/tracking',
  path: '/pipeline/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimatingEstimatesRoute = EstimatingEstimatesRouteImport.update({
  id: '/estimating/estimates',
  path: '/estimating/estimates',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmCustomersRoute = CrmCustomersRouteImport.update({
  id: '/crm/customers',
  path: '/crm/customers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crm/customers': typeof CrmCustomersRoute
  '/estimating/estimates': typeof EstimatingEstimatesRoute
  '/pipeline/tracking': typeof PipelineTrackingRoute
  '/projects/active': typeof ProjectsActiveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crm/customers': typeof CrmCustomersRoute
  '/estimating/estimates': typeof EstimatingEstimatesRoute
  '/pipeline/tracking': typeof PipelineTrackingRoute
  '/projects/active': typeof ProjectsActiveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crm/customers': typeof CrmCustomersRoute
  '/estimating/estimates': typeof EstimatingEstimatesRoute
  '/pipeline/tracking': typeof PipelineTrackingRoute
  '/projects/active': typeof ProjectsActiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crm/customers'
    | '/estimating/estimates'
    | '/pipeline/tracking'
    | '/projects/active'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crm/customers'
    | '/estimating/estimates'
    | '/pipeline/tracking'
    | '/projects/active'
  id:
    | '__root__'
    | '/'
    | '/crm/customers'
    | '/estimating/estimates'
    | '/pipeline/tracking'
    | '/projects/active'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrmCustomersRoute: typeof CrmCustomersRoute
  EstimatingEstimatesRoute: typeof EstimatingEstimatesRoute
  PipelineTrackingRoute: typeof PipelineTrackingRoute
  ProjectsActiveRoute: typeof ProjectsActiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/active': {
      id: '/projects/active'
      path: '/projects/active'
      fullPath: '/projects/active'
      preLoaderRoute: typeof ProjectsActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline/tracking': {
      id: '/pipeline/tracking'
      path: '/pipeline/tracking'
      fullPath: '/pipeline/tracking'
      preLoaderRoute: typeof PipelineTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimating/estimates': {
      id: '/estimating/estimates'
      path: '/estimating/estimates'
      fullPath: '/estimating/estimates'
      preLoaderRoute: typeof EstimatingEstimatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/customers': {
      id: '/crm/customers'
      path: '/crm/customers'
      fullPath: '/crm/customers'
      preLoaderRoute: typeof CrmCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrmCustomersRoute: CrmCustomersRoute,
  EstimatingEstimatesRoute: EstimatingEstimatesRoute,
  PipelineTrackingRoute: PipelineTrackingRoute,
  ProjectsActiveRoute: ProjectsActiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
